name: Tests

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: unit-test
            command: make clean && make check && echo $? # || echo $?
          - mame: black box
            command: make clean && CRASH_TEST_EXT_ARGS="--duration=500" make blackbox_asan_crash_test && echo $? # || echo $?
          - mame: white box
            command: make clean && CRASH_TEST_EXT_ARGS="--duration=500" make whitebox_asan_crash_test && echo $? # || echo $?
    steps:
    
      - name: Pre
        run: |
          sudo apt-get update -y && sudo apt-get install -y build-essential libgflags-dev libsnappy-dev ninja-build
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: ${{ matrix.name }}
        run:  ${{ matrix.command }}
        
# ####in progress####
#   fuzz-test:
#     uses: speedb-io/rocksdb/.github/workflows/fuzz-test@main
